#  vim:ts=2:sts=2:sw=2:et
#
#  Author: Hari Sekhon
#  Date: 2020-07-08 13:36:32 +0100 (Wed, 08 Jul 2020)
#
#  https://github.com/HariSekhon/DevOps-Bash-tools
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

version: '3'

services:
  gerrit:
    hostname: gerrit
    image: gerritcodereview/gerrit:${VERSION:-latest}
    ports:
      - 8080:8080
      - 29418:29418
